# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_title',
            field=models.CharField(default=b'\xe0\xa4\xb6\xe0\xa5\x8d\xe0\xa4\xb0\xe0\xa5\x80', max_length=100, verbose_name=b'Title'),
        ),
    ]
